// resources/js/Pages/Usuarios/Index.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { ref, computed } from 'vue';
const props = defineProps({ users: Object, search: String });
const busqueda = ref(props.search || '');
const total = computed(() => props.users.total || props.users.data.length);
const usuariosFiltrados = computed(() => {
    const term = busqueda.value.trim().toLowerCase();
    if (!term) return props.users.data;
    return props.users.data.filter((u) =>
        [u.nombre, u.apellido, u.email, ...(u.roles?.map(r => r.name) || [])]
            .filter(Boolean)
            .some((value) => value.toLowerCase().includes(term))
    );
});
</script>

<template>
    <Head title="Usuarios" />
    <AuthenticatedLayout>
        <template #header>
            <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-100">Usuarios</h2>
                    <p class="text-sm text-gray-500 dark:text-gray-400">Gestión, control y consulta de usuarios del sistema.</p>
                </div>
            </div>
        </template>
        <div class="py-8">
            <div class="mx-auto max-w-3xl space-y-8 sm:px-6 lg:px-8">
                <div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">
                    <div class="border-b border-gray-100 px-4 py-3 flex items-center justify-between dark:border-gray-700">
                        <div>
                            <h3 class="text-base font-semibold text-gray-800 dark:text-gray-100">Usuarios</h3>
                            <p class="text-xs text-gray-500 dark:text-gray-400">{{ usuariosFiltrados.length }} usuarios registrados</p>
                        </div>
                        <Link :href="route('usuarios.create')" class="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
                            </svg>
                            Nuevo usuario
                        </Link>
                    </div>
                    <div class="max-h-96 overflow-auto">
                        <table class="min-w-full text-left text-sm text-gray-700 dark:text-gray-300">
                            <thead class="bg-gray-50 text-xs uppercase text-gray-500 dark:bg-gray-900 dark:text-gray-400">
                                <tr>
                                    <th class="px-3 py-2">Nombre</th>
                                    <th class="px-3 py-2">Correo</th>
                                    <th class="px-3 py-2">Roles</th>
                                    <th class="px-3 py-2">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="user in usuariosFiltrados" :key="user.id" class="odd:bg-white even:bg-gray-50 dark:odd:bg-gray-800 dark:even:bg-gray-700/50">
                                    <td class="px-3 py-2 align-top">{{ user.nombre }} {{ user.apellido }}</td>
                                    <td class="px-3 py-2 align-top">{{ user.email }}</td>
                                    <td class="px-3 py-2 align-top">
                                        <span v-for="role in user.roles" :key="role.id" class="inline-flex items-center rounded-full bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 mr-1">
                                            {{ role.name }}
                                        </span>
                                    </td>
                                    <td class="px-3 py-2 align-top">
                                        <Link :href="route('usuarios.edit', user.id)" class="text-indigo-600 hover:underline mr-2">Editar</Link>
                                        <Link as="button" method="delete" :href="route('usuarios.destroy', user.id)" class="text-red-600 hover:underline">Eliminar</Link>
                                    </td>
                                </tr>
                                <tr v-if="!usuariosFiltrados.length">
                                    <td colspan="4" class="px-3 py-4 text-center text-gray-500 dark:text-gray-400">Sin datos</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

// frontend/src/app/pages/usuarios/usuarios.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MainLayoutComponent } from '../../layouts/main-layout/main-layout.component';
import { UsuarioService, Usuario } from '../../services/usuario.service';
import Swal from 'sweetalert2';

@Component({
    selector: 'app-usuarios',
    standalone: true,
    imports: [CommonModule, FormsModule, MainLayoutComponent],
    templateUrl: './usuarios.component.html'
})
export class UsuariosComponent implements OnInit {
    usuarios: Usuario[] = [];
    loading = true;
    search = '';
    showForm = false;

    userForm: any = {
        nombre: '',
        apellido: '',
        email: '',
        password: '',
        rol: 'OPERADOR',
        estado: 'ACTIVO'
    };
    editingId: number | null = null;

    constructor(private usuarioService: UsuarioService) { }

    ngOnInit() { this.loadData(); }

    loadData() {
        this.loading = true;
        this.usuarioService.getUsuarios(1, this.search).subscribe({
            next: (res) => {
                this.usuarios = res.data;
                this.loading = false;
            },
            error: () => this.loading = false
        });
    }

    onSearch() { this.loadData(); }

    saveUser() {
        if (!this.userForm.nombre || !this.userForm.email) {
            Swal.fire('Error', 'Nombre y Email son requeridos', 'error');
            return;
        }

        const action = this.editingId
            ? this.usuarioService.update(this.editingId, this.userForm)
            : this.usuarioService.create(this.userForm);

        action.subscribe({
            next: () => {
                Swal.fire('Éxito', this.editingId ? 'Usuario actualizado' : 'Usuario creado', 'success');
                this.closeForm();
                this.loadData();
            },
            error: (err) => Swal.fire('Error', err.error.message || 'Error al procesar', 'error')
        });
    }

    editUser(u: Usuario) {
        this.editingId = u.id;
        this.userForm = { ...u, password: '' }; // Don't show password
        this.showForm = true;
    }

    closeForm() {
        this.showForm = false;
        this.editingId = null;
        this.userForm = {
            nombre: '',
            apellido: '',
            email: '',
            password: '',
            rol: 'OPERADOR',
            estado: 'ACTIVO'
        };
    }

    deleteUsuario(id: number) {
        Swal.fire({
            title: '¿Estás seguro?', text: 'Esta acción no se puede revertir', icon: 'warning',
            showCancelButton: true, confirmButtonColor: '#ef4444', cancelButtonColor: '#64748b',
            confirmButtonText: 'Sí, eliminar', cancelButtonText: 'Cancelar'
        }).then(result => {
            if (result.isConfirmed) {
                this.usuarioService.delete(id).subscribe(() => {
                    Swal.fire('Eliminado', 'Usuario eliminado', 'success');
                    this.loadData();
                });
            }
        });
    }
}

<app-main-layout>
    <div class="p-6 lg:p-8">
        <!-- Header -->
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
            <div>
                <h1 class="text-3xl font-black text-primary tracking-tight">Usuarios del Sistema</h1>
                <p class="text-secondary mt-1 tracking-tight">Administración de cuentas y permisos de acceso.</p>
            </div>
            <div class="flex items-center gap-3">
                <button (click)="showForm = !showForm"
                    class="btn-primary h-12 px-6 shadow-lg shadow-blue-500/20 hover:shadow-blue-500/30 active:scale-95 transition-all">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                    </svg>
                    <span>{{ showForm ? 'Cerrar Formulario' : 'Nuevo Usuario' }}</span>
                </button>
            </div>
        </div>

        <!-- Integrated Top Form Section -->
        <div *ngIf="showForm" class="mb-10 animate-fade-in">
            <div class="card p-0 overflow-hidden border-t-4 border-blue-500 shadow-2xl">
                <div class="px-8 py-6 border-b border-white/5 bg-gray-500/5 flex items-center justify-between">
                    <div>
                        <div class="text-[10px] font-black text-blue-500 uppercase tracking-widest mb-1">Control de
                            Acceso</div>
                        <h3 class="text-2xl font-black text-primary tracking-tight">Registrar Usuario</h3>
                        <p class="text-xs text-muted mt-1">Crea nuevas credenciales de acceso al sistema.</p>
                    </div>
                    <button (click)="closeForm()"
                        class="p-2 text-muted hover:text-white bg-white/5 hover:bg-white/10 rounded-full transition-all">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div class="px-8 py-8">
                    <form (submit)="saveUser()" class="space-y-6">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Nombre <span
                                        class="text-red-500">*</span></label>
                                <input type="text" [(ngModel)]="userForm.nombre" name="nombre"
                                    class="input-field h-11 text-sm bg-gray-50/5" placeholder="Ej: Maria">
                            </div>
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Apellido <span
                                        class="text-red-500">*</span></label>
                                <input type="text" [(ngModel)]="userForm.apellido" name="apellido"
                                    class="input-field h-11 text-sm bg-gray-50/5" placeholder="Ej: Gonzalez">
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Correo Electrónico <span
                                        class="text-red-500">*</span></label>
                                <input type="email" [(ngModel)]="userForm.email" name="email"
                                    class="input-field h-11 text-sm bg-gray-50/5" placeholder="usuario@ejemplo.com">
                            </div>
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Contraseña <span *ngIf="!editingId"
                                        class="text-red-500">*</span></label>
                                <input type="password" [(ngModel)]="userForm.password" name="password"
                                    class="input-field h-11 text-sm bg-gray-50/5"
                                    [placeholder]="editingId ? 'Dejar en blanco para mantener' : 'Contraseña segura'">
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Rol del Usuario <span
                                        class="text-red-500">*</span></label>
                                <select [(ngModel)]="userForm.rol" name="rol"
                                    class="input-field h-11 text-sm bg-gray-50/5">
                                    <option value="ADMIN">Administrador</option>
                                    <option value="OPERADOR">Operador</option>
                                    <option value="CONSULTA">Consulta</option>
                                </select>
                            </div>
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Estado</label>
                                <select [(ngModel)]="userForm.estado" name="estado"
                                    class="input-field h-11 text-sm bg-gray-50/5">
                                    <option value="ACTIVO">Activo</option>
                                    <option value="INACTIVO">Inactivo</option>
                                </select>
                            </div>
                        </div>

                        <div class="flex justify-end pt-6 border-t border-white/5 mt-6">
                            <button type="submit"
                                class="btn-primary w-full md:w-auto px-8 h-11 shadow-xl shadow-blue-500/20 hover:scale-[1.02] active:scale-95 transition-all font-bold tracking-wide">
                                {{ editingId ? 'Actualizar Usuario' : 'Crear Usuario' }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Table Section -->
        <div class="card overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full text-left">
                    <thead
                        class="bg-gray-500/5 text-muted text-[10px] font-black uppercase tracking-widest border-b border-white/5">
                        <tr>
                            <th class="px-6 py-5">Usuario</th>
                            <th class="px-6 py-5">Rol / Permisos</th>
                            <th class="px-6 py-5">Estado</th>
                            <th class="px-6 py-5">Fecha Registro</th>
                            <th class="px-6 py-5 text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-white/5 font-medium">
                        <tr *ngIf="loading" class="animate-pulse">
                            <td colspan="5" class="px-6 py-20 text-center text-muted">Cargando usuarios...</td>
                        </tr>
                        <tr *ngFor="let u of usuarios" class="hover:bg-gray-500/5 transition-colors group">
                            <td class="px-6 py-5">
                                <div class="flex items-center gap-3">
                                    <div
                                        class="h-10 w-10 rounded-full bg-indigo-500/10 flex items-center justify-center text-indigo-500 font-bold border border-indigo-500/20">
                                        {{ u.nombre.charAt(0) }}{{ u.apellido.charAt(0) }}
                                    </div>
                                    <div class="flex flex-col">
                                        <span class="text-sm font-bold text-primary">{{ u.nombre }} {{ u.apellido
                                            }}</span>
                                        <span class="text-xs text-muted">{{ u.email }}</span>
                                    </div>
                                </div>
                            </td>
                            <td class="px-6 py-5">
                                <span
                                    class="px-3 py-1 rounded-full text-[10px] font-black tracking-wider bg-blue-500/10 text-blue-500 border border-blue-500/20">
                                    {{ u.rol }}
                                </span>
                            </td>
                            <td class="px-6 py-5">
                                <span [class]="u.estado === 'ACTIVO' ? 'badge-emerald' : 'badge-red'">
                                    {{ u.estado }}
                                </span>
                            </td>
                            <td class="px-6 py-5 text-sm text-muted">
                                {{ u.created_at | date:'mediumDate' }}
                            </td>
                            <td class="px-6 py-5 text-right">
                                <div class="flex items-center justify-end gap-1">
                                    <button (click)="editUser(u)"
                                        class="p-2 text-muted hover:text-blue-500 hover:bg-blue-500/10 rounded-lg transition-all">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                            viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                        </svg>
                                    </button>
                                    <button (click)="deleteUsuario(u.id)"
                                        class="p-2 text-muted hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-all">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                            viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                        </svg>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</app-main-layout>
