// frontend/src/app/pages/reportes/reportes.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ReporteService } from '../../services/reporte.service';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import Swal from 'sweetalert2';

interface Area { id: number; nombre: string; }
interface Clasificacion { id: number; nombre: string; prefijo: string; }
interface Ubicacion { id: number; nombre: string; }
interface Personal { id: number; nombre: string; apellido: string; area_id?: number; }

@Component({
    selector: 'app-reportes',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './reportes.component.html'
})
export class ReportesComponent implements OnInit {
    loading = false;

    // Filter data
    areas: Area[] = [];
    clasificaciones: Clasificacion[] = [];
    ubicaciones: Ubicacion[] = [];
    personal: Personal[] = [];
    allPersonal: Personal[] = [];

    // Stats data
    resumen: any = { total_activos: 0, valor_total: 0 };
    activosPorClasificacion: { clasificacion: string; cantidad: number }[] = [];
    maxClasificacion: number = 0;

    // Selected filters
    selectedAreaId: number | null = null;
    selectedClasificacionId: number | null = null;
    selectedUbicacionId: number | null = null;
    selectedPersonalId: number | null = null;
    selectedEstado: string | null = null;
    estados: string[] = ['BUENO', 'REGULAR', 'MALO'];

    constructor(
        private reporteService: ReporteService,
        private http: HttpClient,
        private cdr: ChangeDetectorRef
    ) { }

    ngOnInit() {
        this.loadFilterData();
    }

    loadFilterData() {
        const apiUrl = environment.apiUrl;

        this.http.get<Area[]>(`${apiUrl}/areas/all`).subscribe({
            next: (data) => this.areas = data,
            error: (err) => console.error('Error loading areas:', err)
        });

        // Initial stats load without filters
        this.loadStats();

        this.http.get<Clasificacion[]>(`${apiUrl}/clasificaciones`).subscribe({
            next: (data) => this.clasificaciones = data,
            error: (err) => console.error('Error loading clasificaciones:', err)
        });

        this.http.get<Ubicacion[]>(`${apiUrl}/ubicaciones/all`).subscribe({
            next: (data) => this.ubicaciones = data,
            error: (err) => console.error('Error loading ubicaciones:', err)
        });

        this.http.get<Personal[]>(`${apiUrl}/personal/all`).subscribe({
            next: (data) => {
                this.allPersonal = data;
                this.filterPersonalByArea();
            },
            error: (err) => console.error('Error loading personal:', err)
        });
    }

    loadStats() {
        const apiUrl = environment.apiUrl;
        const params = new URLSearchParams();
        if (this.selectedAreaId) params.append('area_id', this.selectedAreaId.toString());
        if (this.selectedUbicacionId) params.append('ubicacion_id', this.selectedUbicacionId.toString());
        if (this.selectedPersonalId) params.append('personal_id', this.selectedPersonalId.toString());
        if (this.selectedClasificacionId) params.append('clasificacion_id', this.selectedClasificacionId.toString());
        if (this.selectedEstado) params.append('estado', this.selectedEstado);

        const queryString = params.toString();
        const suffix = queryString ? '?' + queryString : '';

        this.http.get<any>(`${apiUrl}/reportes/resumen${suffix}`).subscribe({
            next: (data) => {
                console.log('ReportesComponent: Resumen received:', data);
                this.resumen = data;
                this.cdr.detectChanges();
            },
            error: (err) => console.error('Error loading resumen:', err)
        });

        this.http.get<any[]>(`${apiUrl}/reportes/activos-por-clasificacion${suffix}`).subscribe({
            next: (data) => {
                console.log('ReportesComponent: Clasificacion data received:', data);
                this.activosPorClasificacion = data;
                this.maxClasificacion = Math.max(...data.map((d: any) => d.cantidad), 1);
                this.cdr.detectChanges();
            },
            error: (err) => console.error('Error loading stats:', err)
        });
    }

    onAreaChange() {
        this.selectedPersonalId = null; // Reset personal selection when area changes
        this.filterPersonalByArea();
        this.loadStats();
    }

    onFilterChange() {
        this.loadStats();
    }

    filterPersonalByArea() {
        if (this.selectedAreaId) {
            this.personal = this.allPersonal.filter(p => p.area_id === this.selectedAreaId);
        } else {
            this.personal = [...this.allPersonal];
        }
    }

    clearFilters() {
        this.selectedAreaId = null;
        this.selectedClasificacionId = null;
        this.selectedUbicacionId = null;
        this.selectedPersonalId = null;
        this.selectedEstado = null;
        this.filterPersonalByArea();
        this.loadStats();
    }

    hasActiveFilters(): boolean {
        return !!(this.selectedAreaId || this.selectedClasificacionId || this.selectedUbicacionId || this.selectedPersonalId || this.selectedEstado);
    }

    downloadReport(reportId: string) {
        this.loading = true;
        Swal.fire({
            title: 'Generando Reporte',
            text: 'Por favor espere mientras procesamos el documento...',
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading();
            }
        });

        const filters: any = {};
        if (this.selectedAreaId) filters.area_id = this.selectedAreaId;
        if (this.selectedEstado) filters.estado = this.selectedEstado;
        if (this.selectedClasificacionId) filters.clasificacion_id = this.selectedClasificacionId;
        if (this.selectedUbicacionId) filters.ubicacion_id = this.selectedUbicacionId;
        if (this.selectedPersonalId) filters.personal_id = this.selectedPersonalId;

        this.reporteService.descargarReporte(reportId, Object.keys(filters).length > 0 ? filters : undefined).subscribe({
            next: (blob) => {
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${reportId}_${new Date().toISOString().slice(0, 10)}.pdf`;
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
                this.loading = false;
                Swal.close();
                Swal.fire('Éxito', 'Reporte descargado correctamente', 'success');
                this.cdr.detectChanges();
            },
            error: () => {
                this.loading = false;
                Swal.close();
                Swal.fire('Error', 'No se pudo generar el reporte en este momento', 'error');
                this.cdr.detectChanges();
            }
        });
    }
}


    <div class="p-6 lg:p-8">
        <!-- Header -->
        <div class="mb-8 text-center lg:text-left">
            <h1 class="text-4xl font-black text-gray-900 dark:text-white tracking-tight">Centro de Reportes</h1>
            <p class="text-lg text-gray-600 dark:text-gray-400 mt-2 max-w-2xl">Gestione la información estratégica de
                activos fijos.
                Exportación directa en formato PDF listo para impresión y auditoría.</p>
        </div>

        <!-- Filters Section -->
        <div class="card mb-8 p-6">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-blue-500" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
                    </svg>
                    Filtros de Reporte
                </h3>
                <button *ngIf="hasActiveFilters()" (click)="clearFilters()"
                    class="text-xs text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white flex items-center gap-1 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    Limpiar filtros
                </button>
            </div>

            <p class="text-sm text-gray-500 dark:text-gray-400 mb-4">Seleccione los filtros deseados antes de descargar
                un reporte. Los
                filtros se aplicarán a todos los reportes.</p>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
                <!-- Area Filter -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Área</label>
                    <select [(ngModel)]="selectedAreaId" (ngModelChange)="onAreaChange()" class="input-field w-full">
                        <option [ngValue]="null">Todas las áreas</option>
                        <option *ngFor="let area of areas; let i = index" [ngValue]="area.id">{{ (i +
                            1).toString().padStart(2, '0') }} {{ area.nombre }}</option>
                    </select>
                </div>

                <!-- Ubicacion Filter -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Ubicación</label>
                    <select [(ngModel)]="selectedUbicacionId" (ngModelChange)="onFilterChange()"
                        class="input-field w-full">
                        <option [ngValue]="null">Todas las ubicaciones</option>
                        <option *ngFor="let u of ubicaciones; let i = index" [ngValue]="u.id">{{ (i +
                            1).toString().padStart(2, '0') }} {{ u.nombre }}</option>
                    </select>
                </div>

                <!-- Personal Filter -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Responsable</label>
                    <select [(ngModel)]="selectedPersonalId" (ngModelChange)="onFilterChange()"
                        class="input-field w-full">
                        <option [ngValue]="null">Todos los responsables</option>
                        <option *ngFor="let p of personal; let i = index" [ngValue]="p.id">{{ (i +
                            1).toString().padStart(2, '0') }} {{ p.nombre }} {{ p.apellido }}</option>
                    </select>
                </div>

                <!-- Clasificacion Filter -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Clasificación</label>
                    <select [(ngModel)]="selectedClasificacionId" (ngModelChange)="onFilterChange()"
                        class="input-field w-full">
                        <option [ngValue]="null">Todas las clasificaciones</option>
                        <option *ngFor="let c of clasificaciones" [ngValue]="c.id">{{ c.prefijo }} {{ c.nombre }}
                        </option>
                    </select>
                </div>

                <!-- Estado Filter -->
                <div>
                    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Estado</label>
                    <select [(ngModel)]="selectedEstado" (ngModelChange)="onFilterChange()" class="input-field w-full">
                        <option [ngValue]="null">Todos los estados</option>
                        <option *ngFor="let estado of estados" [ngValue]="estado">{{ estado }}</option>
                    </select>
                </div>
            </div>

            <div *ngIf="hasActiveFilters()" class="mt-4 p-3 bg-blue-500/10 border border-blue-500/30 rounded-lg">
                <p class="text-sm text-blue-600 dark:text-blue-300">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline mr-1" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Los reportes se generarán con los filtros seleccionados aplicados.
                </p>
            </div>
        </div>

        <!-- Statistics Section -->
        <div class="card mb-8 p-6">
            <div class="flex flex-col md:flex-row items-center justify-between gap-4 mb-6">
                <h3 class="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-green-600 dark:text-green-400"
                        fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                    Estadísticas de Activos Fijos
                </h3>

                <!-- General Report Button -->
                <button (click)="downloadReport('inventario-general')" [disabled]="loading"
                    class="btn-primary flex items-center gap-2 px-6 py-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Generar Reporte General
                </button>
            </div>

            <!-- Summary Cards -->
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                <div
                    class="bg-blue-50 dark:bg-gradient-to-br dark:from-blue-600/20 dark:to-blue-800/10 border border-blue-200 dark:border-blue-500/20 rounded-xl p-4 text-center">
                    <p class="text-3xl font-black text-blue-600 dark:text-blue-400">{{ resumen.total_activos | number }}
                    </p>
                    <p class="text-xs text-blue-800/60 dark:text-gray-400 mt-1">Total Activos</p>
                </div>
                <div
                    class="bg-green-50 dark:bg-gradient-to-br dark:from-green-600/20 dark:to-green-800/10 border border-green-200 dark:border-green-500/20 rounded-xl p-4 text-center">
                    <p class="text-3xl font-black text-green-600 dark:text-green-400">{{ resumen.activos_buenos | number
                        }}</p>
                    <p class="text-xs text-green-800/60 dark:text-gray-400 mt-1">Estado Bueno</p>
                </div>
                <div
                    class="bg-yellow-50 dark:bg-gradient-to-br dark:from-yellow-600/20 dark:to-yellow-800/10 border border-yellow-200 dark:border-yellow-500/20 rounded-xl p-4 text-center">
                    <p class="text-3xl font-black text-yellow-600 dark:text-yellow-400">{{ resumen.activos_regulares |
                        number }}</p>
                    <p class="text-xs text-yellow-800/60 dark:text-gray-400 mt-1">Estado Regular</p>
                </div>
                <div
                    class="bg-red-50 dark:bg-gradient-to-br dark:from-red-600/20 dark:to-red-800/10 border border-red-200 dark:border-red-500/20 rounded-xl p-4 text-center">
                    <p class="text-3xl font-black text-red-600 dark:text-red-400">{{ resumen.activos_malos | number }}
                    </p>
                    <p class="text-xs text-red-800/60 dark:text-gray-400 mt-1">Estado Malo</p>
                </div>
            </div>

            <!-- Bar Chart - Assets by Classification -->
            <h4 class="text-sm font-semibold text-gray-800 dark:text-gray-300 mb-3">Activos por Clasificación</h4>
            <div class="space-y-2 max-h-64 overflow-y-auto pr-2">
                <div *ngFor="let item of activosPorClasificacion" class="flex items-center gap-3">
                    <div class="w-32 text-xs text-gray-600 dark:text-gray-400 truncate" [title]="item.clasificacion">{{
                        item.clasificacion
                        || 'Sin clasificar' }}</div>
                    <div class="flex-1 bg-gray-200 dark:bg-gray-700/50 rounded-full h-5 overflow-hidden">
                        <div class="h-full bg-gradient-to-r from-blue-600 to-blue-500 dark:from-blue-500 dark:to-blue-400 rounded-full flex items-center justify-end pr-2 transition-all duration-500"
                            [style.width.%]="(item.cantidad / maxClasificacion) * 100">
                            <span class="text-[10px] font-bold text-white">{{ item.cantidad }}</span>
                        </div>
                    </div>
                </div>
                <div *ngIf="activosPorClasificacion.length === 0" class="text-center text-gray-500 py-4">
                    No hay datos de clasificación disponibles
                </div>
            </div>
        </div>
    </div>

// resources/js/Pages/Activos/Reportes.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import { computed, onMounted, ref, watch } from 'vue';
import { Chart } from 'chart.js/auto';

const page = usePage();
const municipalityName = computed(() => page.props.system?.nombre_alcaldia || 'SGAF');

const props = defineProps({
    activos: { type: Array, default: () => [] },
    totales: { type: Object, default: () => ({ cantidad: 0, valor: 0 }) },
    areas: { type: Array, default: () => [] },
    ubicaciones: { type: Array, default: () => [] },
    clasificaciones: { type: Array, default: () => [] },
    filters: { type: Object, default: () => ({}) },
    activosList: { type: Array, default: () => [] },
    personal: { type: Array, default: () => [] },
    areaLocationMap: { type: Object, default: () => ({}) },
});

const filtroInventario = useForm({
    area_id: props.filters?.area_id || '',
    ubicacion_id: props.filters?.ubicacion_id || '',
    personal_id: props.filters?.personal_id || '',
    clasificacion_id: props.filters?.clasificacion_id || '',
    estado: props.filters?.estado || '',
});

// Computed Filters
const filteredPersonal = computed(() => {
    if (!filtroInventario.area_id) {
        return props.personal;
    }
    // Convert to numbers for strict comparison
    const areaIdNumber = Number(filtroInventario.area_id);
    const filtered = props.personal.filter(p => {
        const personalAreaId = Number(p.area_id);
        return personalAreaId === areaIdNumber;
    });
    return filtered;
});

const filteredUbicaciones = computed(() => {
    if (!filtroInventario.area_id) return props.ubicaciones;
    const allowedIds = props.areaLocationMap[filtroInventario.area_id] || [];
    return props.ubicaciones.filter(u => allowedIds.includes(u.id));
});

// Watch Area Change
watch(() => filtroInventario.area_id, (newVal, oldVal) => {
    // Reset dependant filters if area changes
    if (newVal !== oldVal && newVal !== props.filters?.area_id) { 
        filtroInventario.ubicacion_id = '';
        filtroInventario.personal_id = '';
        // Optional: Log only on actual changes
        if (newVal) {
            const filtered = props.personal.filter(p => Number(p.area_id) === Number(newVal));
            console.log(`🔍 Área seleccionada: ${newVal} → ${filtered.length} responsable(s) disponible(s)`);
        }
    }
});

const currencySymbol = computed(() => page.props.system?.moneda || 'C$');
const formatCurrency = (value) => {
    if (value === null || value === undefined || value === '') return '-';
    return `${currencySymbol.value}${Number(value).toLocaleString('es-ES', { minimumFractionDigits: 2 })}`;
};

const filtroTrazabilidad = useForm({
    desde: '',
    hasta: '',
    activo_id: '',
    area_id: '',
    personal_id: '',
});

const estados = [
    { value: 'BUENO', label: 'Bueno' },
    { value: 'REGULAR', label: 'Regular' },
    { value: 'MALO', label: 'Malo' },
];

const aplicarInventario = () => {
    filtroInventario.get(route('activos.reportes'), {
        preserveState: true,
        preserveScroll: true,
        replace: true,
    });
};

const urlInventario = computed(() => route('activos.reportes.inventario.export', filtroInventario.data()));
const urlInventarioPdf = computed(() => route('activos.reportes.inventario.pdf', filtroInventario.data()));
const urlTrazabilidad = computed(() => route('activos.reportes.trazabilidad.export', filtroTrazabilidad.data()));
const urlTrazabilidadPdf = computed(() => route('activos.reportes.trazabilidad.pdf', filtroTrazabilidad.data()));

// Chart References
const chartStatus = ref(null);
const chartArea = ref(null);

onMounted(() => {
    
    // Assets by Status
    const statusCounts = props.activos.reduce((acc, curr) => {
        acc[curr.estado] = (acc[curr.estado] || 0) + 1;
        return acc;
    }, {});
    
    new Chart(document.getElementById('chart-status'), {
        type: 'doughnut',
        data: {
            labels: Object.keys(statusCounts),
            datasets: [{
                data: Object.values(statusCounts),
                backgroundColor: ['#10B981', '#F59E0B', '#EF4444', '#6366F1'],
            }]
        },
        options: { responsive: true, maintainAspectRatio: false }
    });

    // Assets by Area (Top 5)
    const areaCounts = props.activos.reduce((acc, curr) => {
        const area = curr.area || 'Sin Área';
        acc[area] = (acc[area] || 0) + 1;
        return acc;
    }, {});
    
    // Sort by count
    const sortedAreas = Object.entries(areaCounts).sort((a,b) => b[1] - a[1]).slice(0, 5);

    new Chart(document.getElementById('chart-area'), {
        type: 'bar',
        data: {
            labels: sortedAreas.map(a => a[0]),
            datasets: [{
                label: 'Cantidad de Activos',
                data: sortedAreas.map(a => a[1]),
                backgroundColor: '#6366F1',
                borderRadius: 5,
            }]
        },
        options: { 
            responsive: true, 
            maintainAspectRatio: false,
            plugins: { legend: { display: false } }
        }
    });
});
</script>

<template>
    <Head title="Reportes de activos" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <div class="flex items-center gap-2 text-xl font-semibold leading-tight text-gray-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h10m-6 6h12" />
                        </svg>
                        <span>Reportes de activos</span>
                    </div>
                    <p class="text-sm text-gray-500">Inventario filtrable y exportaciones de trazabilidad.</p>
                </div>
                <div class="flex gap-2 text-sm">
                    <a :href="route('activos.index')" class="inline-flex items-center gap-2 rounded-md border border-gray-200 px-3 py-2 text-gray-700 shadow-sm transition hover:border-indigo-300 hover:text-indigo-700">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 5h18M9 3v2m6-2v2M5 9h14v10H5z" />
                        </svg>
                        Inventario
                    </a>
                    <a :href="route('activos.trazabilidad')" class="inline-flex items-center gap-2 rounded-md border border-gray-200 px-3 py-2 text-gray-700 shadow-sm transition hover:border-indigo-300 hover:text-indigo-700">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                        </svg>
                        Trazabilidad
                    </a>
                    <a :href="route('activos.etiquetas-qr')" class="inline-flex items-center gap-2 rounded-md border border-purple-200 px-3 py-2 text-purple-700 shadow-sm transition hover:border-purple-300 hover:bg-purple-50">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
                        </svg>
                        Etiquetas QR
                    </a>
                </div>
            </div>
        </template>

        <div class="py-8">
            <div class="mx-auto max-w-7xl space-y-8 sm:px-6 lg:px-8">
                <div class="grid gap-4 sm:grid-cols-3">
                    <div class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
                        <div class="flex items-center gap-2 text-sm text-gray-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14M5 12l4-4m-4 4l4 4" />
                            </svg>
                            <span>Activos filtrados</span>
                        </div>
                        <p class="text-2xl font-semibold text-gray-900">{{ totales.cantidad }}</p>
                    </div>
                    <div class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
                        <div class="flex items-center gap-2 text-sm text-gray-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 8c-1.657 0-3 1.12-3 2.5S10.343 13 12 13s3 1.12 3 2.5S13.657 18 12 18m0-10v-2m0 12v2" />
                            </svg>
                            <span>Valor total</span>
                        </div>
                        <p class="text-2xl font-semibold text-indigo-700">{{ formatCurrency(totales.valor || 0) }}</p>
                    </div>
                    <div class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
                        <div class="flex items-center gap-2 text-sm text-gray-500">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4 12h16M4 12l4-4m-4 4l4 4" />
                            </svg>
                            <span>Promedio</span>
                        </div>
                        <p class="text-2xl font-semibold text-amber-600">{{ formatCurrency(totales.cantidad ? (totales.valor || 0) / totales.cantidad : 0) }}</p>
                    </div>
                </div>

                <!-- Charts Section -->
                <div class="grid gap-6 md:grid-cols-2">
                    <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
                        <h3 class="text-lg font-semibold text-gray-800 mb-4">Estado de Activos</h3>
                        <div class="h-64">
                            <canvas id="chart-status"></canvas>
                        </div>
                    </div>
                    <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
                        <h3 class="text-lg font-semibold text-gray-800 mb-4">Top Áreas con más Activos</h3>
                        <div class="h-64">
                            <canvas id="chart-area"></canvas>
                        </div>
                    </div>
                </div>

                <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
                    <div class="flex flex-wrap items-center justify-between gap-3">
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900">Reporte de inventario</h3>
                            <p class="text-sm text-gray-500">Filtra y exporta en CSV o PDF.</p>
                        </div>
                        <div class="flex gap-2 text-sm">
                            <a :href="urlInventarioPdf" class="inline-flex items-center gap-2 rounded-md bg-red-600 px-3 py-2 font-semibold text-white shadow-sm transition hover:bg-red-700">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v12m0 0l-4-4m4 4l4-4M4 20h16" />
                                </svg>
                                PDF
                            </a>
                            <a :href="urlInventario" class="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 font-semibold text-white shadow-sm transition hover:bg-indigo-700">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v12m0 0l-4-4m4 4l4-4M4 20h16" />
                                </svg>
                                CSV
                            </a>
                        </div>
                    </div>

                    <form class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5" @submit.prevent="aplicarInventario">
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Área</label>
                            <select v-model="filtroInventario.area_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todas</option>
                                <option v-for="area in areas" :key="area.id" :value="area.id">{{ String(area.id).padStart(2, '0') }} - {{ area.nombre }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Ubicación</label>
                            <select v-model="filtroInventario.ubicacion_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todas</option>
                                <option v-for="ub in filteredUbicaciones" :key="ub.id" :value="ub.id">{{ ub.nombre }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Responsable</label>
                            <select v-model="filtroInventario.personal_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todos</option>
                                <option v-if="filteredPersonal.length === 0 && filtroInventario.area_id" disabled>No hay personal en esta área</option>
                                <option v-for="per in filteredPersonal" :key="per.id" :value="per.id">{{ per.nombre }} {{ per.apellido }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Clasificación</label>
                            <select v-model="filtroInventario.clasificacion_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todas</option>
                                <option v-for="clas in clasificaciones" :key="clas.id" :value="clas.id">{{ String(clas.id).padStart(3, '0') }} - {{ clas.nombre }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Estado</label>
                            <select v-model="filtroInventario.estado" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todos</option>
                                <option v-for="opt in estados" :key="opt.value" :value="opt.value">{{ opt.label }}</option>
                            </select>
                        </div>
                        <div class="sm:col-span-2 lg:col-span-5 flex justify-end">
                            <button
                                type="submit"
                                class="inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-700 focus:ring-offset-1"
                            >
                                Aplicar filtros
                            </button>
                        </div>
                    </form>

                    <div class="mt-6 overflow-auto">
                        <table class="min-w-full divide-y divide-gray-100 text-left text-sm text-gray-700">
                            <thead class="bg-gray-50 text-xs uppercase text-gray-500">
                                <tr>
                                    <th class="px-4 py-3">#</th>
                                    <th class="px-4 py-3">Código</th>
                                    <th class="px-4 py-3">Activo</th>
                                    <th class="px-4 py-3">Área</th>
                                    <th class="px-4 py-3">Clasificación</th>
                                    <th class="px-4 py-3">Ubicación</th>
                                    <th class="px-4 py-3">Responsable</th>
                                    <th class="px-4 py-3">Estado</th>
                                    <th class="px-4 py-3">Precio</th>
                                    <th class="px-4 py-3">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(a, index) in props.activos" :key="a.id" class="border-b border-gray-100 hover:bg-gray-50">
                                    <td class="px-4 py-3 font-mono text-xs text-gray-500">{{ index + 1 }}</td>
                                    <td class="px-4 py-3 font-mono text-xs text-gray-600">{{ a.codigo_inventario }}</td>
                                    <td class="px-4 py-3 font-medium text-gray-900">{{ a.nombre_activo }}</td>
                                    <td class="px-4 py-3 text-gray-700">{{ a.area }}</td>
                                    <td class="px-4 py-3 text-gray-700">{{ a.clasificacion }}</td>
                                    <td class="px-4 py-3 text-gray-700">{{ a.ubicacion }}</td>
                                    <td class="px-4 py-3 text-gray-700">{{ a.responsable || 'No asignado' }}</td>
                                    <td class="px-4 py-3 text-gray-700">{{ a.estado }}</td>
                                    <td class="px-4 py-3 text-gray-900">{{ formatCurrency(a.precio_adquisicion) }}</td>
                                    <td class="px-4 py-3">
                                        <div class="flex gap-2">
                                            <a 
                                                :href="`/activos/${a.id}/acta-asignacion`" 
                                                target="_blank"
                                                class="inline-flex items-center gap-1 rounded-md bg-blue-600 px-2 py-1 text-xs font-medium text-white shadow-sm transition hover:bg-blue-700"
                                                title="Descargar Acta de Asignación"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                </svg>
                                                Acta
                                            </a>
                                            <a 
                                                :href="`/activos/${a.id}/qr`" 
                                                target="_blank"
                                                class="inline-flex items-center gap-1 rounded-md bg-purple-600 px-2 py-1 text-xs font-medium text-white shadow-sm transition hover:bg-purple-700"
                                                title="Ver Código QR"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
                                                </svg>
                                                QR
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr v-if="!props.activos.length">
                                    <td colspan="10" class="px-4 py-4 text-center text-gray-500">Sin registros con los filtros aplicados</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
                    <div class="flex flex-wrap items-center justify-between gap-3">
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900">Reporte de trazabilidad</h3>
                            <p class="text-sm text-gray-500">Exporta movimientos con filtros en CSV o PDF.</p>
                        </div>
                        <div class="flex gap-2 text-sm">
                            <a :href="urlTrazabilidadPdf" class="inline-flex items-center gap-2 rounded-md bg-red-600 px-3 py-2 font-semibold text-white shadow-sm transition hover:bg-red-700">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v12m0 0l-4-4m4 4l4-4M4 20h16" />
                                </svg>
                                PDF
                            </a>
                            <a :href="urlTrazabilidad" class="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 font-semibold text-white shadow-sm transition hover:bg-indigo-700">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v12m0 0l-4-4m4 4l4-4M4 20h16" />
                                </svg>
                                CSV
                            </a>
                        </div>
                    </div>

                    <div class="mt-4 grid gap-4 sm:grid-cols-5">
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Desde</label>
                            <input v-model="filtroTrazabilidad.desde" type="date" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500" />
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Hasta</label>
                            <input v-model="filtroTrazabilidad.hasta" type="date" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500" />
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Activo</label>
                            <select v-model="filtroTrazabilidad.activo_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todos</option>
                                <option v-for="ac in activosList" :key="ac.id" :value="ac.id">{{ ac.codigo_inventario }} - {{ ac.nombre_activo }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Área destino</label>
                            <select v-model="filtroTrazabilidad.area_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todas</option>
                                <option v-for="area in areas" :key="area.id" :value="area.id">{{ area.nombre }}</option>
                            </select>
                        </div>
                        <div>
                            <label class="text-xs font-semibold text-gray-700">Responsable destino</label>
                            <select v-model="filtroTrazabilidad.personal_id" class="mt-1 w-full rounded-md border border-gray-200 px-3 py-2 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                                <option value="">Todos</option>
                                <option v-for="per in personal" :key="per.id" :value="per.id">{{ per.nombre }} {{ per.apellido }}</option>
                            </select>
                        </div>
                    </div>

                    <p class="mt-3 text-xs text-gray-500">El botón descarga con los filtros actuales.</p>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
