// frontend/src/app/pages/ubicaciones/ubicaciones.component.ts
import { Component, OnInit, ChangeDetectorRef, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UbicacionService, Area, Ubicacion } from '../../services/ubicacion.service';
import Swal from 'sweetalert2';

@Component({
    selector: 'app-ubicaciones',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './ubicaciones.component.html'
})
export class UbicacionesComponent implements OnInit {
    activeTab: 'areas' | 'ubicaciones' = 'areas';
    showForm = false;
    activeFormTab: 'area' | 'ubicacion' = 'area';

    areas: Area[] = [];
    ubicaciones: Ubicacion[] = [];
    loading = true;
    searchText = '';

    // Area form
    areaForm = { nombre: '', ubicacion_id: null as number | null, estado: 'ACTIVO' };
    editingAreaId: number | null = null;

    // Ubicacion form
    ubicacionForm = { nombre: '', direccion: '', estado: 'ACTIVO' };
    editingUbicacionId: number | null = null;

    constructor(
        private ubicacionService: UbicacionService,
        private cdr: ChangeDetectorRef
    ) { }

    ngOnInit() {
        this.loadData();
    }

    loadData() {
        this.loadAreas();
        this.loadUbicaciones();
    }

    loadAreas() {
        this.loading = true;
        this.ubicacionService.getAllAreas().subscribe({
            next: (res) => {
                this.areas = res;
                this.checkLoading();
            },
            error: () => this.checkLoading()
        });
    }

    loadUbicaciones() {
        this.loading = true;
        this.ubicacionService.getAllUbicaciones().subscribe({
            next: (res) => {
                this.ubicaciones = res;
                this.checkLoading();
            },
            error: () => this.checkLoading()
        });
    }

    checkLoading() {
        this.loading = false;
        this.cdr.detectChanges();
    }

    get filteredAreas(): Area[] {
        if (!this.searchText) return this.areas;
        const search = this.searchText.toLowerCase();
        return this.areas.filter(a =>
            a.nombre.toLowerCase().includes(search) ||
            (a.ubicacion_nombre?.toLowerCase().includes(search) || false)
        );
    }

    get filteredUbicaciones(): Ubicacion[] {
        if (!this.searchText) return this.ubicaciones;
        const search = this.searchText.toLowerCase();
        return this.ubicaciones.filter(u =>
            u.nombre.toLowerCase().includes(search) ||
            (u.direccion?.toLowerCase().includes(search) || false)
        );
    }

    openForm(type: 'area' | 'ubicacion') {
        this.activeFormTab = type;
        this.showForm = true;
        this.resetForms();
    }

    closeForm() {
        this.showForm = false;
        this.editingAreaId = null;
        this.editingUbicacionId = null;
        this.resetForms();
    }

    resetForms() {
        if (!this.editingAreaId) {
            this.areaForm = { nombre: '', ubicacion_id: null, estado: 'ACTIVO' };
        }
        if (!this.editingUbicacionId) {
            this.ubicacionForm = { nombre: '', direccion: '', estado: 'ACTIVO' };
        }
    }

    // AREA METHODS
    saveArea() {
        if (!this.areaForm.nombre) {
            Swal.fire('Atención', 'El nombre del área es obligatorio', 'warning');
            return;
        }

        const action = this.editingAreaId
            ? this.ubicacionService.updateArea(this.editingAreaId, this.areaForm)
            : this.ubicacionService.createArea(this.areaForm);

        action.subscribe({
            next: () => {
                Swal.fire({
                    icon: 'success',
                    title: this.editingAreaId ? 'Actualizado' : 'Creado',
                    text: `El área se ha ${this.editingAreaId ? 'actualizado' : 'creado'} correctamente.`,
                    timer: 2000,
                    showConfirmButton: false
                });
                this.closeForm();
                this.loadData();
            },
            error: (err) => {
                console.error('Error saving area:', err);
                const msg = err.error?.message || err.message || 'Error desconocido del servidor';
                Swal.fire('Error', `No se pudo procesar el área: ${msg}`, 'error');
            }
        });
    }

    startEditArea(area: Area) {
        this.editingAreaId = area.id;
        this.areaForm = {
            nombre: area.nombre,
            ubicacion_id: area.ubicacion_id ?? null,
            estado: area.estado
        };
        this.openForm('area');
    }

    deleteArea(id: number) {
        Swal.fire({
            title: '¿Estás seguro?',
            text: 'Esta acción no se puede revertir',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#ef4444',
            cancelButtonColor: '#64748b',
            confirmButtonText: 'Sí, eliminar',
            cancelButtonText: 'Cancelar'
        }).then(result => {
            if (result.isConfirmed) {
                this.ubicacionService.deleteArea(id).subscribe({
                    next: () => {
                        Swal.fire('Eliminado', 'El área ha sido eliminada', 'success');
                        this.loadData();
                    },
                    error: (err) => Swal.fire('Error', 'No se pudo eliminar el área', 'error')
                });
            }
        });
    }

    // UBICACION METHODS
    saveUbicacion() {
        if (!this.ubicacionForm.nombre) {
            Swal.fire('Atención', 'El nombre de la ubicación es obligatorio', 'warning');
            return;
        }

        const action = this.editingUbicacionId
            ? this.ubicacionService.updateUbicacion(this.editingUbicacionId, this.ubicacionForm)
            : this.ubicacionService.createUbicacion(this.ubicacionForm);

        action.subscribe({
            next: () => {
                Swal.fire({
                    icon: 'success',
                    title: this.editingUbicacionId ? 'Actualizado' : 'Creado',
                    text: `La ubicación se ha ${this.editingUbicacionId ? 'actualizada' : 'creada'} correctamente.`,
                    timer: 2000,
                    showConfirmButton: false
                });
                this.closeForm();
                this.loadData();
            },
            error: (err) => {
                console.error('Error saving ubicacion:', err);
                const msg = err.error?.message || err.message || 'Error desconocido del servidor';
                Swal.fire('Error', `No se pudo procesar la ubicación: ${msg}`, 'error');
            }
        });
    }

    startEditUbicacion(ubicacion: Ubicacion) {
        this.editingUbicacionId = ubicacion.id;
        this.ubicacionForm = {
            nombre: ubicacion.nombre,
            direccion: ubicacion.direccion || '',
            estado: ubicacion.estado
        };
        this.openForm('ubicacion');
    }

    deleteUbicacion(id: number) {
        Swal.fire({
            title: '¿Estás seguro?',
            text: 'Esta acción no se puede revertir',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#ef4444',
            cancelButtonColor: '#64748b',
            confirmButtonText: 'Sí, eliminar',
            cancelButtonText: 'Cancelar'
        }).then(result => {
            if (result.isConfirmed) {
                this.ubicacionService.deleteUbicacion(id).subscribe({
                    next: () => {
                        Swal.fire('Eliminado', 'La ubicación ha sido eliminada', 'success');
                        this.loadData();
                    },
                    error: () => Swal.fire('Error', 'No se pudo eliminar la ubicación', 'error')
                });
            }
        });
    }

    getUbicacionNombre(id: number | null | undefined): string {
        if (!id) return 'General / Sin asginar';
        const ubicacion = this.ubicaciones.find(u => u.id === id);
        return ubicacion?.nombre || 'Desconocido';
    }

    // Keyboard Shortcuts
    @HostListener('window:keydown', ['$event'])
    handleKeyboardEvent(event: KeyboardEvent) {
        if (event.ctrlKey && event.altKey && event.key === 'n') {
            event.preventDefault();
            if (this.activeTab === 'areas') {
                this.openForm('area');
            } else if (this.activeTab === 'ubicaciones') {
                this.openForm('ubicacion');
            }
        }
    }
}


    <div class="p-6 lg:p-8">
        <!-- Header -->
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
            <div>
                <h2 class="text-3xl font-black text-primary tracking-tight">Estructura Organizativa</h2>
                <p class="text-secondary mt-1 tracking-tight">Gestión jerárquica de áreas y ubicaciones físicas.</p>
            </div>
        </div>

        <div class="mb-6">
            <div class="relative group">
                <input type="text" [(ngModel)]="searchText"
                    class="input-field w-full !bg-white dark:!bg-white/5 !border-gray-300 dark:!border-white/10 rounded-2xl py-4 pl-14 pr-6 !text-gray-900 dark:!text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all text-lg shadow-xl text-center"
                    placeholder="Buscar en {{ activeTab === 'areas' ? 'Departamentos' : 'Ubicaciones' }}...">
                <div class="absolute inset-y-0 left-0 pl-6 flex items-center pointer-events-none">
                    <svg class="h-6 w-6 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                </div>
                <div *ngIf="searchText" class="absolute inset-y-0 right-0 pr-6 flex items-center">
                    <button (click)="searchText = ''"
                        class="text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
                        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <!-- Navigation Tabs -->
        <div class="flex gap-2 mb-6 overflow-x-auto pb-2">
            <button (click)="activeTab = 'areas'" [class.bg-blue-600]="activeTab === 'areas'"
                [class.text-white]="activeTab === 'areas'" [class.shadow-lg]="activeTab === 'areas'"
                class="px-6 py-3 rounded-xl font-bold text-sm transition-all hover:bg-blue-500 hover:text-white shrink-0">
                Departamentos / Áreas ({{ areas.length }})
            </button>
            <button (click)="activeTab = 'ubicaciones'" [class.bg-blue-600]="activeTab === 'ubicaciones'"
                [class.text-white]="activeTab === 'ubicaciones'" [class.shadow-lg]="activeTab === 'ubicaciones'"
                class="px-6 py-3 rounded-xl font-bold text-sm transition-all hover:bg-blue-500 hover:text-white shrink-0">
                Ubicaciones Físicas ({{ ubicaciones.length }})
            </button>
        </div>

        <!-- Integrated Data Entry Form -->
        <div *ngIf="showForm" class="mb-10 animate-fade-in">
            <div class="card p-0 overflow-hidden border-t-4 border-blue-500 shadow-2xl">
                <!-- Form Switcher Tabs -->
                <div class="flex border-b border-white/5 bg-gray-500/5 justify-between items-center">
                    <h3 class="px-8 py-4 text-sm font-black uppercase tracking-widest text-blue-500">
                        {{ editingAreaId || editingUbicacionId ? 'Editar' : 'Nuevo' }} Registro
                    </h3>
                    <button (click)="closeForm()"
                        class="p-2 mr-4 text-muted hover:text-white bg-white/5 hover:bg-white/10 rounded-full transition-all">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div class="px-8 py-8">
                    <!-- AREA FORM -->
                    <form *ngIf="activeFormTab === 'area'" (ngSubmit)="saveArea()" class="space-y-6">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Nombre del Área <span
                                        class="text-red-500">*</span></label>
                                <input type="text" [(ngModel)]="areaForm.nombre" name="nombre"
                                    class="input-field h-11 text-sm bg-gray-50/5" placeholder="Ej. Recursos Humanos">
                            </div>
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Ubicación Física Asociada</label>
                                <select [(ngModel)]="areaForm.ubicacion_id" name="ubi_id"
                                    class="input-field h-11 text-sm bg-gray-50/5">
                                    <option [ngValue]="null">Sin asignar (General)</option>
                                    <option *ngFor="let u of ubicaciones; let i = index" [value]="u.id">
                                        {{ (i + 1) < 10 ? '0' + (i + 1) : (i + 1) }} {{ u.nombre }} </option>
                                </select>
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Estado Operativo</label>
                                <select [(ngModel)]="areaForm.estado" name="estado"
                                    class="input-field h-11 text-sm bg-gray-50/5">
                                    <option value="ACTIVO">Activo</option>
                                    <option value="INACTIVO">Inactivo</option>
                                </select>
                            </div>
                            <div class="flex justify-end mt-6">
                                <button type="submit"
                                    class="btn-primary w-full md:w-auto px-8 h-11 shadow-xl shadow-blue-500/20 hover:scale-[1.02] active:scale-95 transition-all font-bold tracking-wide">
                                    {{ editingAreaId ? 'Actualizar Área' : 'Guardar Área' }}
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- UBICACION FORM -->
                    <form *ngIf="activeFormTab === 'ubicacion'" (ngSubmit)="saveUbicacion()" class="space-y-6">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Nombre del Edificio / Sitio <span
                                        class="text-red-500">*</span></label>
                                <input type="text" [(ngModel)]="ubicacionForm.nombre" name="nombre_ubi"
                                    class="input-field h-11 text-sm bg-gray-50/5"
                                    placeholder="Ej. Edificio Municipal A">
                            </div>
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Dirección / Referencia</label>
                                <input type="text" [(ngModel)]="ubicacionForm.direccion" name="dir"
                                    class="input-field h-11 text-sm bg-gray-50/5"
                                    placeholder="Ej. Frente al parque central">
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                            <div class="space-y-2">
                                <label class="text-xs font-bold text-muted">Estado</label>
                                <select [(ngModel)]="ubicacionForm.estado" name="estado_ubi"
                                    class="input-field h-11 text-sm bg-gray-50/5">
                                    <option value="ACTIVO">Activo</option>
                                    <option value="INACTIVO">Inactivo</option>
                                </select>
                            </div>
                            <div class="flex justify-end mt-6">
                                <button type="submit"
                                    class="btn-primary w-full md:w-auto px-8 h-11 shadow-xl shadow-blue-500/20 hover:scale-[1.02] active:scale-95 transition-all font-bold tracking-wide">
                                    {{ editingUbicacionId ? 'Actualizar Ubicación' : 'Guardar Ubicación' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- TAB CONTENT -->

        <!-- Areas Section -->
        <div *ngIf="activeTab === 'areas'" class="animate-fade-in">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
                <h3 class="text-xs font-black text-muted uppercase tracking-[0.2em]">Departamentos / Áreas Registradas
                </h3>
                <button (click)="openForm('area')"
                    class="btn-primary h-11 px-6 shadow-lg shadow-blue-500/20 active:scale-95 transition-all font-bold">
                    Nuevo Área
                </button>
            </div>

            <div class="card overflow-hidden">
                <div class="overflow-x-auto">
                    <table class="w-full text-left">
                        <thead>
                            <tr
                                class="bg-gray-500/5 text-muted text-[10px] font-black uppercase tracking-widest border-b border-white/5">
                                <th class="px-6 py-4 w-12">#</th>
                                <th class="px-6 py-4">Nombre del Área</th>
                                <th class="px-6 py-4">Ubicación</th>
                                <th class="px-6 py-4">Estado</th>
                                <th class="px-6 py-4 text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-white/5 font-medium">
                            <tr *ngFor="let area of filteredAreas; let i = index"
                                class="hover:bg-gray-500/5 transition-colors group">
                                <td class="px-6 py-4 text-xs font-black text-muted">{{ i + 1 }}</td>
                                <td class="px-6 py-4 text-sm font-bold text-primary">
                                    <span class="text-blue-500 mr-2 font-mono">
                                        {{ (i + 1) < 10 ? '0' + (i + 1) : (i + 1) }} </span>
                                            {{ area.nombre }}
                                </td>
                                <td class="px-6 py-4 text-xs text-muted">{{ getUbicacionNombre(area.ubicacion_id) }}
                                </td>
                                <td class="px-6 py-4">
                                    <span [class]="area.estado === 'ACTIVO' ? 'badge-emerald' : 'badge-red'">
                                        {{ area.estado }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 text-right">
                                    <div class="flex items-center justify-end gap-1">
                                        <button (click)="startEditArea(area)"
                                            class="p-2 text-muted hover:text-blue-500 hover:bg-blue-500/10 rounded-lg transition-all">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </button>
                                        <button (click)="deleteArea(area.id)"
                                            class="p-2 text-muted hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-all">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- Pagination removed for real-time search -->
            </div>
        </div>

        <!-- Locations Section -->
        <div *ngIf="activeTab === 'ubicaciones'" class="animate-fade-in">
            <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
                <h3 class="text-xs font-black text-muted uppercase tracking-[0.2em]">Ubicaciones Físicas Registradas
                </h3>
                <button (click)="openForm('ubicacion')"
                    class="btn-primary h-11 px-6 shadow-lg shadow-blue-500/20 active:scale-95 transition-all font-bold">
                    Nueva Ubicación
                </button>
            </div>

            <div class="card overflow-hidden">
                <div class="overflow-x-auto">
                    <table class="w-full text-left">
                        <thead>
                            <tr
                                class="bg-gray-500/5 text-muted text-[10px] font-black uppercase tracking-widest border-b border-white/5">
                                <th class="px-6 py-4 w-12">#</th>
                                <th class="px-6 py-4">Ubicación / Sitio</th>
                                <th class="px-6 py-4">Dirección</th>
                                <th class="px-6 py-4">Estado</th>
                                <th class="px-6 py-4 text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-white/5 font-medium">
                            <tr *ngFor="let ubi of filteredUbicaciones; let i = index"
                                class="hover:bg-gray-500/5 transition-colors group">
                                <td class="px-6 py-4 text-xs font-black text-muted">{{ i + 1 }}</td>
                                <td class="px-6 py-4 text-sm font-bold text-primary">
                                    <span class="text-blue-500 mr-2 font-mono">
                                        {{ (i + 1) < 10 ? '0' + (i + 1) : (i + 1) }} </span>
                                            {{ ubi.nombre }}
                                </td>
                                <td class="px-6 py-4 text-xs text-muted truncate max-w-[150px]">{{ ubi.direccion ||
                                    'N/A' }}</td>
                                <td class="px-6 py-4">
                                    <span [class]="ubi.estado === 'ACTIVO' ? 'badge-emerald' : 'badge-red'">
                                        {{ ubi.estado }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 text-right">
                                    <div class="flex items-center justify-end gap-1">
                                        <button (click)="startEditUbicacion(ubi)"
                                            class="p-2 text-muted hover:text-blue-500 hover:bg-blue-500/10 rounded-lg transition-all">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </button>
                                        <button (click)="deleteUbicacion(ubi.id)"
                                            class="p-2 text-muted hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-all">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none"
                                                viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- Pagination removed for real-time search -->
            </div>
        </div>
    </div>

// resources/js/Pages/Ubicaciones/Index.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm, router, usePage, Link } from '@inertiajs/vue3';
import { ref, computed } from 'vue';
import Swal from 'sweetalert2';

const props = defineProps({
    ubicaciones: {
        type: Object,
        default: () => ({ data: [] }),
    },
});

const page = usePage();
const can = (permission) => page.props.auth.user?.permissions?.includes(permission);
const canManage = computed(() => can('catalogos.manage'));

const createForm = useForm({
    nombre: '',
    direccion: '',
    estado: 'ACTIVO',
});

const editForm = useForm({
    id: null,
    nombre: '',
    direccion: '',
    estado: 'ACTIVO',
});

const editing = ref(false);

const startEdit = (ubicacion) => {
    editing.value = true;
    editForm.id = ubicacion.id;
    editForm.nombre = ubicacion.nombre;
    editForm.direccion = ubicacion.direccion || '';
    editForm.estado = ubicacion.estado;
};

const cancelEdit = () => {
    editing.value = false;
    editForm.reset('id', 'nombre', 'direccion', 'estado');
};

const submitCreate = () => {
    createForm.post(route('ubicaciones.store'), {
        onSuccess: () => createForm.reset('nombre'),
    });
};

const submitEdit = () => {
    editForm.put(route('ubicaciones.update', editForm.id), {
        onSuccess: () => {
            cancelEdit();
        },
    });
};

const destroyUbicacion = (id) => {
    Swal.fire({
        title: '¿Estás seguro?',
        text: "Esta acción no se puede revertir",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Sí, eliminar',
        cancelButtonText: 'Cancelar'
    }).then((result) => {
        if (result.isConfirmed) {
            router.delete(route('ubicaciones.destroy', id));
        }
    });
};
</script>

<template>
    <Head title="Ubicaciones" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <div>
                    <h2 class="text-xl font-semibold leading-tight text-gray-800">Ubicaciones</h2>
                    <p class="text-sm text-gray-500">Gestiona ubicaciones físicas o lógicas.</p>
                </div>
            </div>
        </template>

        <div class="py-10">
            <div class="mx-auto max-w-5xl space-y-8 sm:px-6 lg:px-8">
                <div class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
                        <h3 class="text-lg font-semibold text-gray-800">Crear ubicación</h3>
                        <p class="text-sm text-gray-500">Ingresa un nombre único y estado.</p>

                        <form class="mt-4 space-y-4" @submit.prevent="submitCreate">
                            <div>
                                <label class="text-sm font-medium text-gray-700">Nombre</label>
                                <input
                                    v-model="createForm.nombre"
                                    type="text"
                                    class="mt-1 w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    required
                                    maxlength="255"
                                />
                                <p v-if="createForm.errors.nombre" class="mt-1 text-sm text-red-600">
                                    {{ createForm.errors.nombre }}
                                </p>
                            </div>

                            <div>
                                <label class="text-sm font-medium text-gray-700">Dirección</label>
                                <input
                                    v-model="createForm.direccion"
                                    type="text"
                                    class="mt-1 w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    maxlength="500"
                                    placeholder="Ej: Calle Principal #123, Ciudad"
                                />
                                <p v-if="createForm.errors.direccion" class="mt-1 text-sm text-red-600">
                                    {{ createForm.errors.direccion }}
                                </p>
                            </div>

                            <div>
                                <label class="text-sm font-medium text-gray-700">Estado</label>
                                <select
                                    v-model="createForm.estado"
                                    class="mt-1 w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                                    required
                                >
                                    <option value="ACTIVO">ACTIVO</option>
                                    <option value="INACTIVO">INACTIVO</option>
                                </select>
                                <p v-if="createForm.errors.estado" class="mt-1 text-sm text-red-600">
                                    {{ createForm.errors.estado }}
                                </p>
                            </div>

                            <div class="flex justify-end">
                                <button
                                    type="submit"
                                    :disabled="createForm.processing"
                                    class="inline-flex items-center rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-50"
                                >
                                    Guardar
                                </button>
                            </div>
                        </form>
                    </div>

                <div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
                    <div class="flex items-center justify-between border-b border-gray-100 px-6 py-4">
                        <div>
                            <h3 class="text-lg font-semibold text-gray-800">Listado</h3>
                            <p class="text-sm text-gray-500">Selecciona para editar o eliminar.</p>
                        </div>
                    </div>
                    <div class="max-h-[480px] overflow-auto">
                        <table class="min-w-full text-left text-sm text-gray-700">
                            <thead class="bg-gray-50 text-xs uppercase text-gray-500">
                                <tr>
                                    <th class="px-4 py-3">ID</th>
                                    <th class="px-4 py-3">Nombre</th>
                                    <th class="px-4 py-3">Dirección</th>
                                    <th class="px-4 py-3">Estado</th>
                                    <th class="px-4 py-3">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr
                                    v-for="ubicacion in props.ubicaciones.data"
                                    :key="ubicacion.id"
                                    class="border-b border-gray-100 hover:bg-gray-50"
                                >
                                    <td class="px-4 py-3 text-gray-500">{{ ubicacion.id }}</td>
                                    <td class="px-4 py-3 font-medium text-gray-900">{{ ubicacion.nombre }}</td>
                                    <td class="px-4 py-3 text-gray-600">{{ ubicacion.direccion || '-' }}</td>
                                    <td class="px-4 py-3">
                                        <span
                                            class="inline-flex items-center rounded-full px-2 py-1 text-xs font-semibold"
                                            :class="ubicacion.estado === 'ACTIVO'
                                                ? 'bg-green-100 text-green-800'
                                                : 'bg-gray-200 text-gray-700'"
                                        >
                                            {{ ubicacion.estado }}
                                        </span>
                                    </td>
                                    <td class="px-4 py-3 space-x-2 text-sm">
                                        <button
                                            v-if="canManage"
                                            class="inline-flex items-center justify-center rounded-md p-1.5 text-indigo-600 hover:bg-indigo-50 transition"
                                            type="button"
                                            @click="startEdit(ubicacion)"
                                            title="Editar"
                                        >
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                            </svg>
                                        </button>
                                        <button
                                            v-if="canManage"
                                            class="inline-flex items-center justify-center rounded-md p-1.5 text-red-600 hover:bg-red-50 transition"
                                            type="button"
                                            @click="destroyUbicacion(ubicacion.id)"
                                            title="Eliminar"
                                        >
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </td>
                                </tr>
                                <tr v-if="!props.ubicaciones.data.length">
                                    <td colspan="5" class="px-4 py-4 text-center text-gray-500">
                                        Sin registros
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    <!-- Paginación -->
                    <div v-if="props.ubicaciones.links && props.ubicaciones.links.length > 3" class="border-t border-gray-100 px-6 py-4">
                        <div class="flex items-center justify-between">
                            <div class="text-sm text-gray-500">
                                Mostrando {{ props.ubicaciones.from }} a {{ props.ubicaciones.to }} de {{ props.ubicaciones.total }} registros
                            </div>
                            <div class="flex gap-1">
                                <Link
                                    v-for="(link, index) in props.ubicaciones.links"
                                    :key="index"
                                    :href="link.url || '#'"
                                    :class="[
                                        'px-3 py-1.5 text-sm border rounded-md transition',
                                        link.active
                                            ? 'bg-indigo-600 text-white border-indigo-600'
                                            : link.url
                                            ? 'bg-white text-gray-700 border-gray-300 hover:bg-gray-50'
                                            : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
                                    ]"
                                    v-html="link.label"
                                    :preserve-scroll="true"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
