// resources/js/Pages/Auth/Login.vue
<script setup>
import Checkbox from '@/Components/Checkbox.vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

defineProps({
    canResetPassword: {
        type: Boolean,
    },
    status: {
        type: String,
    },
});

const form = useForm({
    email: '',
    password: '',
    remember: false,
});

const submit = () => {
    form.post(route('login'), {
        onFinish: () => form.reset('password'),
    });
};
</script>

<template>
    <GuestLayout>
        <Head title="Iniciar sesión" />

        <!-- Welcome message -->
        <div class="mb-6 text-center">
            <h2 class="text-2xl font-bold text-gray-900">Bienvenido</h2>
            <p class="mt-2 text-sm text-gray-600">Ingresa tus credenciales para continuar</p>
        </div>

        <!-- Status message -->
        <div v-if="status" class="mb-4 rounded-lg bg-green-50 p-4 text-sm font-medium text-green-800 border border-green-200">
            <div class="flex items-center gap-2">
                <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
                <span>{{ status }}</span>
            </div>
        </div>

        <form @submit.prevent="submit" class="space-y-5">
            <!-- Email field -->
            <div>
                <InputLabel for="email" value="Correo electrónico" class="text-gray-700 font-semibold" />
                <div class="relative mt-2">
                    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                        <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
                        </svg>
                    </div>
                    <TextInput
                        id="email"
                        type="email"
                        class="block w-full pl-10 rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                        v-model="form.email"
                        required
                        autofocus
                        autocomplete="username"
                        placeholder="correo@ejemplo.com"
                    />
                </div>
                <InputError class="mt-2" :message="form.errors.email" />
            </div>

            <!-- Password field -->
            <div>
                <InputLabel for="password" value="Contraseña" class="text-gray-700 font-semibold" />
                <div class="relative mt-2">
                    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                        <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                        </svg>
                    </div>
                    <TextInput
                        id="password"
                        type="password"
                        class="block w-full pl-10 rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                        v-model="form.password"
                        required
                        autocomplete="current-password"
                        placeholder="••••••••"
                    />
                </div>
                <InputError class="mt-2" :message="form.errors.password" />
            </div>

            <!-- Remember me and forgot password -->
            <div class="flex items-center justify-between">
                <label class="flex items-center">
                    <Checkbox name="remember" v-model:checked="form.remember" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:ring-indigo-500" />
                    <span class="ml-2 text-sm text-gray-600">Recordarme</span>
                </label>

                <Link
                    v-if="canResetPassword"
                    :href="route('password.request')"
                    class="text-sm font-medium text-indigo-600 hover:text-indigo-500 transition-colors"
                >
                    ¿Olvidaste tu contraseña?
                </Link>
            </div>

            <!-- Submit button -->
            <div class="pt-2">
                <PrimaryButton
                    class="w-full justify-center rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 px-4 py-3 text-sm font-semibold text-white shadow-lg hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition-all duration-200"
                    :class="{ 'opacity-50 cursor-not-allowed': form.processing }"
                    :disabled="form.processing"
                >
                    <svg v-if="form.processing" class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span v-if="form.processing">Iniciando sesión...</span>
                    <span v-else>Iniciar sesión</span>
                </PrimaryButton>
            </div>
        </form>
    </GuestLayout>
</template>

// frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';
import Swal from 'sweetalert2';

@Component({
    selector: 'app-login',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})
export class LoginComponent {
    credentials = {
        email: '',
        password: ''
    };
    isLoading = false;

    constructor(private authService: AuthService, private router: Router) { }

    onSubmit() {
        this.isLoading = true;
        this.authService.login(this.credentials).subscribe({
            next: (res) => {
                this.isLoading = false;
                Swal.fire({
                    icon: 'success',
                    title: '¡Bienvenido!',
                    text: 'Inicio de sesión exitoso',
                    timer: 2000,
                    showConfirmButton: false
                });
                this.router.navigate(['/dashboard']);
            },
            error: (err) => {
                this.isLoading = false;
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'Credenciales inválidas',
                    confirmButtonColor: '#4682B4'
                });
            }
        });
    }
}

<div class="min-h-screen bg-slate-900 flex items-center justify-center p-4">
  <div class="w-full max-w-md bg-slate-800/50 backdrop-blur-xl border border-slate-700/50 rounded-2xl overflow-hidden shadow-2xl animate-fade-in">
    <div class="p-8">
      <div class="flex justify-center mb-8">
        <div class="w-20 h-20 bg-steel-500 rounded-2xl flex items-center justify-center shadow-[0_0_30px_rgba(70,130,180,0.4)] animate-pulse-glow">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-1.17-12.29c.428-1.503 1.055-2.91 1.848-4.212m10.123 4.212c-.428-1.503-1.055-2.91-1.848-4.212M12 11c0-3.517 1.009-6.799 2.753-9.571m1.17 12.29c-.428 1.503-1.055 2.91-1.848 4.212M12 11V7m0 11v-4m0 4h.01m-6.938-4h13.856" />
          </svg>
        </div>
      </div>

      <h2 class="text-3xl font-orbitron font-bold text-center text-white mb-2">SGAF 2.0</h2>
      <p class="text-slate-400 text-center mb-8 font-inter">Sistema de Gestión de Activos Fijos</p>

      <form (ngSubmit)="onSubmit()" #loginForm="ngForm" class="space-y-6">
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-2 font-inter">Correo Electrónico</label>
          <input 
            type="email" 
            name="email"
            [(ngModel)]="credentials.email"
            required
            class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-steel-500 focus:border-transparent transition-all outline-none font-inter"
            placeholder="admin@example.com"
          >
        </div>

        <div>
          <div class="flex items-center justify-between mb-2">
            <label class="text-sm font-medium text-slate-300 font-inter">Contraseña</label>
            <a href="#" class="text-xs text-steel-400 hover:text-steel-300 transition-colors">¿Olvidaste tu contraseña?</a>
          </div>
          <input 
            type="password" 
            name="password"
            [(ngModel)]="credentials.password"
            required
            class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-steel-500 focus:border-transparent transition-all outline-none font-inter"
            placeholder="••••••••"
          >
        </div>

        <button 
          type="submit"
          [disabled]="!loginForm.form.valid || isLoading"
          class="w-full bg-steel-500 hover:bg-steel-600 disabled:opacity-50 disabled:cursor-not-allowed text-white font-orbitron font-bold py-4 rounded-xl shadow-lg shadow-steel-500/20 transform hover:-translate-y-0.5 transition-all flex items-center justify-center space-x-2"
        >
          <span *ngIf="!isLoading">INICIAR SESIÓN</span>
          <span *ngIf="isLoading" class="flex items-center">
            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            PROCESANDO...
          </span>
        </button>
      </form>
    </div>
    
    <div class="p-4 bg-slate-800/80 text-center border-t border-slate-700/50">
      <p class="text-xs text-slate-500 font-inter">© 2026 SGAF2 - Municipal Alcala. Todos los derechos reservados.</p>
    </div>
  </div>
</div>
